dashboard/urls.py
from django.urls import path
from . import views


app_name = 'dashboard'

urlpatterns=[
    path("dashboard/", views.dashboard, name='dashboard')
]

loginpage/urls.py
from django.urls import path
from . import views

app_name = 'loginpage'

urlpatterns = [
    path("loginpage/", views.login, name='loginpage'),
]

members/urls.py
from django.urls import path
from . import views


app_name = 'members'

urlpatterns=[
    path("members/", views.members, name='members'),
]

my_tennis_club/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("members.urls")),
    path('', include("products.urls")),
    path('', include('loginpage.urls')),
    path('', include('dashboard.urls')),
    path('', include('registration.urls')),
    path('', include('reset.urls')),
]

products/urls.py
from django.urls import path
from . import views


app_name = 'products'

urlpatterns=[
    path("products/", views.products, name='products'),
    path('products/delete_product/<int:product_id>/', views.delete_product, name='delete_product'),
    path('products/edit_product/<int:product_id>/', views.edit_product, name='edit_product'),

]

registration/urls.py
from django.urls import path
from . import views

app_name = 'registration'

urlpatterns = [
    path('signup/', views.register, name='signup'),
]

reset/urls.py
from django.urls import path
from . import views

app_name = 'reset'

urlpatterns = [
    path('reset/', views.resetting, name='reset'),
]

members/models.py
from django.db import models

# Create your models here.
class Member(models.Model):
    firstname = models.CharField(max_length=255)
    lastname  = models.CharField(max_length=255)
    age = models.IntegerField(null=True)
    phone = models.IntegerField(null=True)
    joined_date = models.DateField(null=True)
    email = models.CharField(max_length=255,default='example@example.com')

products/models.py
from django.db import models

# Create your models here.
class Product(models.Model):
    product_type = models.CharField(max_length = 100)
    product_name = models.CharField(max_length=100)
    product_status = models.CharField(max_length=10, choices = [("old","old"), ("new", "new")])
    product_price = models.DecimalField(max_digits=10, decimal_places= 2)

products/forms.py
from django import forms
from .models import Product

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['product_type', 'product_name', 'product_status', 'product_price']

dashboard/views.py
from django.shortcuts import render
from django.contrib.auth.models import User



from django.shortcuts import render

def dashboard(request):
    myusers = User.objects.all()
    context = {
        'myusers': myusers,
    }
    return render(request, "dashboard.html", context)

loginpage/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login as auth_login
from django.contrib import messages
from django.http import JsonResponse
from django.contrib.auth.models import User
import json
from django.http import JsonResponse




def login(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]

        user = authenticate(request, username=username, password=password)

        if user is not None:
            auth_login(request, user)
            return redirect("dashboard:dashboard")
        else:
            messages.error(request, "Incorrect username or password. Please try again !.")
    return render(request, "loginpage.html")

members/views.py
from django.shortcuts import render
from .models import Member

def members(request):
    mymembers = Member.objects.all()
    context = {
        'mymembers': mymembers,
    }
    return render(request, 'members.html', context)

products/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect
from .models import Product
from .forms import ProductForm
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render, get_object_or_404,redirect


# Form to add products to the table 
def products(request):
    form = ProductForm()
    if request.method == 'POST':
        form = ProductForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('products:products')
    products = Product.objects.all()  
    return render(request, "products.html", {'products': products, 'form': form})

@csrf_exempt
# deleting the item using the remove button in the product table 
def delete_product(request, product_id):
    try:
        product = Product.objects.get(pk=product_id)
        product.delete()
        response_data = {'message': 'Removed'}
    except Product.DoesNotExist: 
        response_data = {'message': 'Not found'}
    return JsonResponse(response_data)

# View for editing the product.
def edit_product(request, product_id):
    product = get_object_or_404(product, pk=product_id)

    if request.method == "POST":
        form = ProductForm(request.POST, instance=product)
        if form.is_valid():
            form.save()
            return redirect('products:products')
        else:
            form = ProductForm(instance=product)
            return render(request, 'edit_product.html', {'form': form, 'product': product})

reset/views.py
from django.contrib.auth import login
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import messages

def resetting(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        password1 = request.POST.get('password1')
        password2 = request.POST.get('password2')
        user = User.objects.get(email=email)
        user.set_password(password1)
        user.save()
        messages.success(request, "Account created!")
        return redirect('loginpage:loginpage')
    return render(request, 'registration/reset.html')

templates/base.html
<!DOCTYPE HTML>
<html lang="en" >
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Income Generating App</title>
        <link rel="shortcut icon" type="img/png" href="img/turn.png">
        <!-- External CSS -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
        <!-- DataTables CSS -->
        <link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/jquery.dataTables.css">
        <!-- External JavaScript Libraries -->
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>
        <!-- Your Custom JavaScript -->
        <script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.js"></script>
    </head>
    
    <body id="body" >
        <!-- add the css files  -->
        {% block stylings %} 

        {% endblock %}

        <!-- display the html content from pages -->
        {% block content %}

        {% endblock %}

        <!-- display javascript from other pages javascript pages -->
        {% block javascripts %}

        {% endblock %}
    </body>
</html>

templates/cards/dashboard_cards.html
{% load static %}

{%block content%}
  <!-- cards section -->

  <div id="cards_rows" class="row max-auto">
    <div id="cards_card"  class="col-sm-4">
      <div  class="card ">
        <div class="card-body">
          <h5 id="card_title" class="card-title">New Members</h5>
          <p class="card-text">Add new members here.</p>
          <a href="#" class="btn btn-primary btn-sm">Add Member</a>
        </div>
      </div>
    </div>
    <div id="cards_card"  class="col-sm-4">
      <div class="card">
        <div class="card-body ">
          <h5 id="card_title" class="card-title ">New Product</h5>
          <p class="card-text">Add a new product here.</p>
          <a href="{% url 'products:products' %}" class="btn btn-primary btn-sm">Add product</a>
        </div>
      </div>
    </div>
  </div>
  
{%endblock%}

templates/dashboard.html
{% extends 'base.html' %}

{% load static %}

{% block stylings %}
    <link rel="stylesheet" href="{% static 'css/dashboard.css' %}" />
{% endblock %}

{% block content %}

<div id="viewport">
  {% include 'default/sidebar.html' %}

    <!-- Content -->
    <div id="content">
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <ul class="nav navbar-nav navbar-right">
            <li>
              <a href="#"><i class="zmdi zmdi-notifications text-danger"></i>
              </a>
            </li>
            <li><a href="#">Test User</a></li>
          </ul>
        </div>
      </nav>
      <div class="container-fluid">
        <h1>Membership Dashboard</h1>
        <p>Please remember to Log out when <code>#done with your work.</code>.</p>
      </div>
    </div>
  </div>

  {% include 'cards/dashboard_cards.html' %}
  {% include 'tables/products_display.html' %}
  {% include 'newmembers.html' %}

  </div> 


{% endblock %}

templates/default/sidebar.html
{% load static %}

{% block content %}

  <div id="sidebar">
    <header>
      <a href="#">Dashboard</a>
    </header>
    <ul class="nav">
      <li >
        <a href="{% url 'dashboard:dashboard' %}">
          <i class="fas fa-home"></i> Dashboard</a>
      </li>
      <li>
        <a href="{% url 'members:members' %}">
          <i class="fas fa-users me-2"></i>  Members</a>
      </li>
      <li>
        <a href="{% url 'products:products' %}">
          <i class="fas fa-shopping-cart me-2"></i> Products</a>
      </li>
      <li>
        <a href="{% url 'loginpage:loginpage' %}">
          <i class="fas fa-sign-out-alt me-2"></i> Logout</a>
      </li>
    </ul>
  </div>
  
{%endblock%}

templates/loginpage.html
{% extends 'base.html' %}
{% load static %}

{% block stylings %}
    <link rel="stylesheet" href="{% static 'css/loginpage.css' %}" />

{% endblock %}

{% block content %}

    <section class="background-radial-gradient overflow-hidden">  
        <div class="container px-4 py-5 px-md-5 text-center text-lg-start my-5">
            <div class="row gx-lg-5 align-items-center mb-5">
                <div class="col-lg-6 mb-5 mb-lg-0" style="z-index: 10">
                    <h1 class="my-5 display-5 fw-bold ls-tight" style="color: hsl(218, 81%, 95%)">
                        Welcome to the Club <br />
                        <span style="color: hsl(218, 81%, 75%)">Enjoy Each Game You Play</span>
                    </h1>
                    <p class="mb-4 opacity-70" style="color: hsl(218, 81%, 85%)">
                        We are here to make this sport enjoyable!
                    </p>
                </div>
        
                <div class="col-lg-6 mb-5 mb-lg-0 position-relative">
                    <div id="radius-shape-1" class="position-absolute rounded-circle shadow-5-strong"></div>
                    <div id="radius-shape-2" class="position-absolute shadow-5-strong"></div>
                    <div class="card bg-glass">
                    <div class="card-body px-4 py-3 px-md-5">
                        <form id="login-form" method="post" action="{% url 'loginpage:loginpage' %}" >
                            {% csrf_token %}
                            <div class="form_h1">Login</div>                       
                            {% if messages %}
                                {% for message in messages %}
                                    <div class="alert alert-{{ message.tags }}">
                                        {{ message }}
                                    </div>
                                {% endfor %}
                            {% endif %}                      
                            <div class="form-outline mb-3">
                                <label class="form-label" for="username">User Name</label>
                                <input type="text" id="username" class="form-control" name="username" required autocomplete="username" />
                            </div>                       
                            <div class="form-outline mb-3 mb-4">
                                <label class="form-label" for="password">Password</label>
                                <input type="password" id="password" class="form-control" name="password" required autocomplete="current-password" />
                            </div>                      
                            <div class="form-check d-flex justify-content-center mb-4">
                                <input class="form-check-input me-2" type="checkbox" value="" id="subscribe" checked />
                                <label class="form-check-label" for="subscribe">
                                    Subscribe to our newsletter
                                </label>
                            </div>
                            <div class="text-center  margin-bottom: 26px;">
                                <a href="{% url 'registration:signup' %}" id="show-signup" class="btn btn-link">Sign Up</a> |
                                <a href="{% url 'reset:reset' %}" class="btn btn-link">Forgot Password</a>
                            </div>                      
                            <button type="submit" class="btn btn-primary btn-block mb-4">Login</button>
                        </form>
                        
                    </div>
                </div>
            </div>
        </div>
    </section>
  
   
{% endblock %}

templates/members.html
{% extends 'base.html' %}
{% load static %}


{% block stylings %}
  <link rel="stylesheet" href="{% static 'css/members.css' %}" />
  <link rel="stylesheet" href="{% static 'css/dashboard.css' %}" />
{% endblock %}

{% block content %}
{% include 'default/sidebar.html' %}
  <div class="welcome_div">
    
    <h1 class="members_h1">Welcome to Membership Board</h1>
    <h1 class="members_tag">
      The all-in-one <span class="members_span">membership</span> platform for players
    </h1>
  </div>

  {% include 'tables/members_details.html' %}

 
 
  
{% endblock %}

templates/newmembers.html
{% extends 'base.html' %}
{% load static %}

{% block stylings %}
    <link rel="stylesheet" href="{% static 'css/members.css' %}" />
{% endblock %}

{% block content %}

    <div class="newmembers_container">
        <table id="newMemberTable" class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">First name</th>
                    <th scope="col">Last name</th>
                    <th scope="col">Email</th>
                    <th scope="col">Registration</th>
                </tr>
            </thead>
            <tbody>
                {% for user in myusers %}
                <tr>
                    <th scope="row">{{ user.id }}</th>
                    <td>{{ user.first_name }}</td>
                    <td>{{ user.last_name }}</td>
                    <td>{{ user.email }} </td>
                    <td><button class="add_button" data-user-id="{{ user.id }}">Add</button></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    

    <!-- Include the JavaScript file -->
    {% block javascripts %}
        <script src="{% static 'javascript/members.js' %}"></script>
    {% endblock %}

{% endblock %}

templates/products.html
{% extends 'base.html' %}

{% load static %}


{% block stylings %}
    <link rel="stylesheet" href="{% static 'css/products.css' %}" />
    <link rel="stylesheet" href="{% static 'css/productcards.css' %}" />
    <link rel="stylesheet" href="{% static 'css/dashboard.css' %}" />
{% endblock %}

{% block content %}

  {% include 'default/sidebar.html' %}
    
  <h1 class="members_h1">All Products</h1>
  <p class="members_p">All the Products Are Posted In This Page</p>

    <h1 id="product_table_h1">Add Product</h1>
 
    <form autocomplete="off" id="products_form" method="post" action="{% url 'products:products' %}">
      {% csrf_token %}

      <div class="imput_content">

        <div class="lable_div">
          <label for="{{ form.product_type.id_for_label }}">Product Type</label>
          {{ form.product_type }}
        </div>
        
        <div class="lable_div">
          <label for="{{ form.product_name.id_for_label }}">Product Name</label>
          {{ form.product_name }}
        </div>
  
        <div class="lable_div">
          <label for="{{ form.product_status.id_for_label }}">Product Status</label>
          {{ form.product_status }}
        </div>
    
  
        <div class="lable_div">
          <label for="{{ form.product_price.id_for_label }}">Product Price</label>
          {{ form.product_price }}
        </div>
      </div>
  
      <button type="submit">Submit</button>
  </form>


  <div class="products_table_container">
    <table id="product_table" class="table table-striped table-bordered">
      <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Product Type</th>
        <th scope="col">Product Name</th>
        <th scope="col">Price</th>
        <th scope="col">Actions</th>
      </tr>
      </thead>
      <tbody>
        {% for product in products %}
          
          <tr data-product-id="{{ product.id }}">

              <th scope="row">{{ forloop.counter }}</th>
              <td>{{ product.product_type }}</td>
              <td>{{ product.product_name }}</td>
              <td>{{ product.product_price }}</td>
              <td>
                <div class="btns_container">

                  <a href="#" class="edit_link" data-product-id="{{ product.id }}" title="Edit">
                    <i class="fas fa-edit"></i> 
                  </a>

                  <a href="#" class="delete_link" title="delete">
                      <i class="fas fa-trash"></i> 
                  </a>

                  <a href="#" class="info_link" title="info">
                      <i class="fas fa-info-circle"></i> 
                  </a>
              </div>
              </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>


  <form id="edit_form" action="/products/edit_product/" method="post">
    {% csrf_token %}
    <a href="#product_table" class="close_link" title="close">
      <i class="fas fa-times"></i>
    </a>
    

    <div class="text">Edit Product</div>
    <div class="inputs_container">
      <div class="form-row">
        <div class="input-data">
          <input type="text" name="product_name" required>
          <div class="underline"></div>
          <label for="product_name">Product Name</label>
        </div>
        <div class="input-data">
          <input type="text" name="product_type" required>
          <div class="underline"></div>
          <label for="product_type">Product Type</label>
        </div>
      </div>
      <div class="form-row">
        <div class="input-data">
          <input type="text" name="product_price" required>
          <div class="underline"></div>
          <label for="product_price">Price</label>
        </div>
      </div>
      <div class="form-row">
        <div class="input-data textarea">
          <textarea name="product_description" rows="8" cols="80" required></textarea>
          <br />
          <div class="underline"></div>
          <label for="product_description">Write your message</label>
          <br />
        </div>
        <div class="form-row submit-btn">
          <div class="input-data">
            <div class="inner"></div>
            <input type="submit" value="submit">
          </div>
        </div>
      </div>
    </div>
  </form>
  

  
  {% block javascripts %}
    <script src="{% static 'javascript/products.js' %}"></script>
  {% endblock %}

{% endblock %}

templates/tables/members_details.html
{% load static %}


{% block content %}

  <div class="members-container">
    <table id="allMembers_talbe" class="table table-striped table-bordered" >
      <thead  >
        <tr >
          <th>FirstName</th>
          <th>LastName</th>
          <th>Contact</th>
          <th>Email</th>
          <th>Age</th>
          
        </tr> 
      </thead>
        <tbody>
          {% for user in myusers %}
          <tr>
              <th scope="row">{{ user.id }}</th>
              <td>{{ user.first_name }}</td>
              <td>{{ user.last_name }}</td>
              <td>{{ user.email }} </td>
              <td><button class="add_button" >Delete</button></td>
          </tr>
          {% endfor %}
      </tbody>
    </table>

    
  </div> 

  
   <!-- Include the JavaScript file -->
   {% block javascripts %}
    <script src="{% static 'javascript/members.js' %}"></script>
  {% endblock %}

{%endblock%}
  
  
  
  
  

templates/tables/products_display.html
{% extends 'base.html' %}
{% load static %}

{% block stylings %}
    <link rel="stylesheet" href="{% static 'css/members.css' %}" />
{% endblock %}

{% block content %}

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save</button>
    </form>

{%endblock%}